// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXylWRWOUsQ2ISS27U7j0szmXe2eMACRA',
    appId: '1:332441676033:web:9b5e42fdbfad85a4551300',
    messagingSenderId: '332441676033',
    projectId: 'flutterprojet-18193',
    authDomain: 'flutterprojet-18193.firebaseapp.com',
    storageBucket: 'flutterprojet-18193.appspot.com',
    measurementId: 'G-R1VJQ0M67H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQo0TJblSQ-RSIDUXl-CPGaY_I7mxNdDI',
    appId: '1:332441676033:android:346374ed5ede0cfc551300',
    messagingSenderId: '332441676033',
    projectId: 'flutterprojet-18193',
    storageBucket: 'flutterprojet-18193.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkYDQVctSvcEHFklSP0bLEQZkmNTgEyk0',
    appId: '1:332441676033:ios:d45798c472f9aec9551300',
    messagingSenderId: '332441676033',
    projectId: 'flutterprojet-18193',
    storageBucket: 'flutterprojet-18193.appspot.com',
    iosClientId: '332441676033-mn136ae3idbs8e4kmujcboa3vjs2iba2.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkYDQVctSvcEHFklSP0bLEQZkmNTgEyk0',
    appId: '1:332441676033:ios:d45798c472f9aec9551300',
    messagingSenderId: '332441676033',
    projectId: 'flutterprojet-18193',
    storageBucket: 'flutterprojet-18193.appspot.com',
    iosClientId: '332441676033-mn136ae3idbs8e4kmujcboa3vjs2iba2.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetFlutter',
  );
}
